CREATE OR REPLACE FUNCTION fantasy_prev_insert()
RETURNS void AS $$
DECLARE fantasy_cursor cursor FOR
	SELECT fantasy.player_id
		, fantasy.gsis_id
		, game.season_year
	FROM public.fantasy
		join public.game on fantasy.gsis_id = game.gsis_id;
begin
	CREATE TEMP TABLE fantasy_prev_off
	(
		gsis_id gameid,
		team_id character varying(3),
		player_id character varying(10),
		prev_amount character varying(10),
		"position" player_pos,
		pass_att real,
		pass_cmp real,
		pass_yds real,
		pass_tds real,
		"int" real,
		rush_att real,
		rush_yds real,
		fumble real,
		targets real,
		rec real,
		rec_yds real,
		yac real,
		ret_yds real,
		td real,
		block_kick real,
		safety real,
		sack real,
		pts_allowed real,
		fg_50 real,
		fg_40 real,
		fg_0 real,
		pat real,
		fg_miss real,
		points real
	) ON COMMIT DROP;

	FOR fantasy_row in fantasy_cursor loop
		begin
			INSERT INTO fantasy_prev_off
			(
				gsis_id,
				team_id,
				player_id,
				prev_amount,
				"position",
				pass_att,
				pass_cmp,
				pass_yds,
				pass_tds,
				"int",
				rush_att,
				rush_yds,
				fumble,
				targets,
				rec,
				rec_yds,
				yac,
				ret_yds,
				td,
				block_kick,
				safety,
				sack,
				pts_allowed,
				fg_50,
				fg_40,
				fg_0,
				pat,
				fg_miss,
				points
			)
			SELECT fantasy_row.gsis_id,
				fantasy.team_id,
				fantasy.player_id,
				'prev2',
				fantasy.position,
				fantasy.pass_att,
				fantasy.pass_cmp,
				fantasy.pass_yds,
				fantasy.pass_tds,
				fantasy.int,
				fantasy.rush_att,
				fantasy.rush_yds,
				fantasy.fumble,
				fantasy.targets,
				fantasy.rec,
				fantasy.rec_yds,
				fantasy.yac,
				fantasy.ret_yds,
				fantasy.td,
				fantasy.block_kick,
				fantasy.safety,
				fantasy.sack,
				fantasy.pts_allowed,
				fantasy.fg_50,
				fantasy.fg_40,
				fantasy.fg_0,
				fantasy.pat,
				fantasy.fg_miss,
				fantasy.points
			FROM public.fantasy
			WHERE fantasy.player_id = fantasy_row.player_id
				and fantasy.gsis_id < fantasy_row.gsis_id
			ORDER BY fantasy.gsis_id DESC
			LIMIT 2;

			INSERT INTO fantasy_prev_off
			(
				gsis_id,
				team_id,
				player_id,
				prev_amount,
				"position",
				pass_att,
				pass_cmp,
				pass_yds,
				pass_tds,
				"int",
				rush_att,
				rush_yds,
				fumble,
				targets,
				rec,
				rec_yds,
				yac,
				ret_yds,
				td,
				block_kick,
				safety,
				sack,
				pts_allowed,
				fg_50,
				fg_40,
				fg_0,
				pat,
				fg_miss,
				points
			)
			SELECT fantasy_row.gsis_id,
				fantasy.team_id,
				fantasy.player_id,
				'prev5',
				fantasy.position,
				fantasy.pass_att,
				fantasy.pass_cmp,
				fantasy.pass_yds,
				fantasy.pass_tds,
				fantasy.int,
				fantasy.rush_att,
				fantasy.rush_yds,
				fantasy.fumble,
				fantasy.targets,
				fantasy.rec,
				fantasy.rec_yds,
				fantasy.yac,
				fantasy.ret_yds,
				fantasy.td,
				fantasy.block_kick,
				fantasy.safety,
				fantasy.sack,
				fantasy.pts_allowed,
				fantasy.fg_50,
				fantasy.fg_40,
				fantasy.fg_0,
				fantasy.pat,
				fantasy.fg_miss,
				fantasy.points
			FROM public.fantasy
			WHERE fantasy.player_id = fantasy_row.player_id
				and fantasy.gsis_id < fantasy_row.gsis_id
			ORDER BY fantasy.gsis_id DESC
			LIMIT 5;

			INSERT INTO fantasy_prev_off
			(
				gsis_id,
				team_id,
				player_id,
				prev_amount,
				"position",
				pass_att,
				pass_cmp,
				pass_yds,
				pass_tds,
				"int",
				rush_att,
				rush_yds,
				fumble,
				targets,
				rec,
				rec_yds,
				yac,
				ret_yds,
				td,
				block_kick,
				safety,
				sack,
				pts_allowed,
				fg_50,
				fg_40,
				fg_0,
				pat,
				fg_miss,
				points
			)
			SELECT fantasy_row.gsis_id,
				fantasy.team_id,
				fantasy.player_id,
				'season',
				fantasy.position,
				cast(avg(fantasy.pass_att) as real),
				cast(avg(fantasy.pass_cmp) as real),
				cast(avg(fantasy.pass_yds) as real),
				cast(avg(fantasy.pass_tds) as real),
				cast(avg(fantasy.int) as real),
				cast(avg(fantasy.rush_att) as real),
				cast(avg(fantasy.rush_yds) as real),
				cast(avg(fantasy.fumble) as real),
				cast(avg(fantasy.targets) as real),
				cast(avg(fantasy.rec) as real),
				cast(avg(fantasy.rec_yds) as real),
				cast(avg(fantasy.yac) as real),
				cast(avg(fantasy.ret_yds) as real),
				cast(avg(fantasy.td) as real),
				cast(avg(fantasy.block_kick) as real),
				cast(avg(fantasy.safety) as real),
				cast(avg(fantasy.sack) as real),
				cast(avg(fantasy.pts_allowed) as real),
				cast(avg(fantasy.fg_50) as real),
				cast(avg(fantasy.fg_40) as real),
				cast(avg(fantasy.fg_0) as real),
				cast(avg(fantasy.pat) as real),
				cast(avg(fantasy.fg_miss) as real),
				cast(avg(fantasy.points) as real)
			FROM public.fantasy
				join public.game on fantasy.gsis_id = game.gsis_id
			WHERE game.season_year = fantasy_row.season_year
				and fantasy.player_id = fantasy_row.player_id
			GROUP BY fantasy.team_id, fantasy.player_id, fantasy.position;

			INSERT INTO fantasy_prev_off
			(
				gsis_id,
				team_id,
				player_id,
				prev_amount,
				"position",
				pass_att,
				pass_cmp,
				pass_yds,
				pass_tds,
				"int",
				rush_att,
				rush_yds,
				fumble,
				targets,
				rec,
				rec_yds,
				yac,
				ret_yds,
				td,
				block_kick,
				safety,
				sack,
				pts_allowed,
				fg_50,
				fg_40,
				fg_0,
				pat,
				fg_miss,
				points
			)
			SELECT fantasy_row.gsis_id,
				fantasy.team_id,
				fantasy.player_id,
				'prevseason',
				fantasy.position,
				cast(avg(fantasy.pass_att) as real),
				cast(avg(fantasy.pass_cmp) as real),
				cast(avg(fantasy.pass_yds) as real),
				cast(avg(fantasy.pass_tds) as real),
				cast(avg(fantasy.int) as real),
				cast(avg(fantasy.rush_att) as real),
				cast(avg(fantasy.rush_yds) as real),
				cast(avg(fantasy.fumble) as real),
				cast(avg(fantasy.targets) as real),
				cast(avg(fantasy.rec) as real),
				cast(avg(fantasy.rec_yds) as real),
				cast(avg(fantasy.yac) as real),
				cast(avg(fantasy.ret_yds) as real),
				cast(avg(fantasy.td) as real),
				cast(avg(fantasy.block_kick) as real),
				cast(avg(fantasy.safety) as real),
				cast(avg(fantasy.sack) as real),
				cast(avg(fantasy.pts_allowed) as real),
				cast(avg(fantasy.fg_50) as real),
				cast(avg(fantasy.fg_40) as real),
				cast(avg(fantasy.fg_0) as real),
				cast(avg(fantasy.pat) as real),
				cast(avg(fantasy.fg_miss) as real),
				cast(avg(fantasy.points) as real)
			FROM public.fantasy
				join public.game on fantasy.gsis_id = game.gsis_id
			WHERE game.season_year = fantasy_row.season_year - 1
				and fantasy.player_id = fantasy_row.player_id
			GROUP BY fantasy.team_id, fantasy.player_id, fantasy.position;

			INSERT INTO fantasy_prev_off
			(
				gsis_id,
				team_id,
				player_id,
				prev_amount,
				"position",
				pass_att,
				pass_cmp,
				pass_yds,
				pass_tds,
				"int",
				rush_att,
				rush_yds,
				fumble,
				targets,
				rec,
				rec_yds,
				yac,
				ret_yds,
				td,
				block_kick,
				safety,
				sack,
				pts_allowed,
				fg_50,
				fg_40,
				fg_0,
				pat,
				fg_miss,
				points
			)
			SELECT fantasy_row.gsis_id,
				fantasy.team_id,
				fantasy.player_id,
				'career',
				fantasy.position,
				cast(avg(fantasy.pass_att) as real),
				cast(avg(fantasy.pass_cmp) as real),
				cast(avg(fantasy.pass_yds) as real),
				cast(avg(fantasy.pass_tds) as real),
				cast(avg(fantasy.int) as real),
				cast(avg(fantasy.rush_att) as real),
				cast(avg(fantasy.rush_yds) as real),
				cast(avg(fantasy.fumble) as real),
				cast(avg(fantasy.targets) as real),
				cast(avg(fantasy.rec) as real),
				cast(avg(fantasy.rec_yds) as real),
				cast(avg(fantasy.yac) as real),
				cast(avg(fantasy.ret_yds) as real),
				cast(avg(fantasy.td) as real),
				cast(avg(fantasy.block_kick) as real),
				cast(avg(fantasy.safety) as real),
				cast(avg(fantasy.sack) as real),
				cast(avg(fantasy.pts_allowed) as real),
				cast(avg(fantasy.fg_50) as real),
				cast(avg(fantasy.fg_40) as real),
				cast(avg(fantasy.fg_0) as real),
				cast(avg(fantasy.pat) as real),
				cast(avg(fantasy.fg_miss) as real),
				cast(avg(fantasy.points) as real)
			FROM public.fantasy
				join public.game on fantasy.gsis_id = game.gsis_id
			WHERE fantasy.player_id = fantasy_row.player_id
				and game.gsis_id < fantasy_row.gsis_id
			GROUP BY fantasy.team_id, fantasy.player_id, fantasy.position;
		end;
	end loop;

	INSERT INTO public.fantasy_prev
	(
		gsis_id,
		team_id,
		player_id,
		prev_amount,
		"position",
		pass_att,
		pass_cmp,
		pass_yds,
		pass_tds,
		"int",
		rush_att,
		rush_yds,
		fumble,
		targets,
		rec,
		rec_yds,
		yac,
		ret_yds,
		td,
		block_kick,
		safety,
		sack,
		pts_allowed,
		fg_50,
		fg_40,
		fg_0,
		pat,
		fg_miss,
		points
	)
	SELECT
		fantasy_prev_off.gsis_id,
		fantasy_prev_off.team_id,
		fantasy_prev_off.player_id,
		fantasy_prev_off.prev_amount,
		fantasy_prev_off.position,
		avg(fantasy_prev_off.pass_att),
		avg(fantasy_prev_off.pass_cmp),
		avg(fantasy_prev_off.pass_yds),
		avg(fantasy_prev_off.pass_tds),
		avg(fantasy_prev_off.int),
		avg(fantasy_prev_off.rush_att),
		avg(fantasy_prev_off.rush_yds),
		avg(fantasy_prev_off.fumble),
		avg(fantasy_prev_off.targets),
		avg(fantasy_prev_off.rec),
		avg(fantasy_prev_off.rec_yds),
		avg(fantasy_prev_off.yac),
		avg(fantasy_prev_off.ret_yds),
		avg(fantasy_prev_off.td),
		avg(fantasy_prev_off.block_kick),
		avg(fantasy_prev_off.safety),
		avg(fantasy_prev_off.sack),
		avg(fantasy_prev_off.pts_allowed),
		avg(fantasy_prev_off.fg_50),
		avg(fantasy_prev_off.fg_40),
		avg(fantasy_prev_off.fg_0),
		avg(fantasy_prev_off.pat),
		avg(fantasy_prev_off.fg_miss),
		avg(fantasy_prev_off.points)
	FROM fantasy_prev_off
	GROUP BY
		fantasy_prev_off.gsis_id,
		fantasy_prev_off.team_id,
		fantasy_prev_off.player_id,
		fantasy_prev_off.prev_amount,
		fantasy_prev_off.position;
end;
$$ LANGUAGE plpgsql;